#!/usr/bin/env python3
"""Self-host a Google Fonts css2 stylesheet.

Why: loading fonts from Google's CDN sends every visitor's IP to Google without
consent. LG Muenchen I, 20 Jan 2022 (Az. 3 O 17493/20) held that this violates
GDPR precisely because a free, privacy-neutral alternative exists. This product
sells a compliance story to EU employers; a third-party font CDN in <head> is
the most-litigated GDPR defect on the open web.

Keeps latin + latin-ext only (the app ships EN + PT), woff2 only.
"""
import os, re, sys, urllib.request

UA = ('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/125.0 Safari/537.36')
KEEP = {'latin', 'latin-ext'}


def get(url, binary=False):
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    data = urllib.request.urlopen(req, timeout=60).read()
    return data if binary else data.decode('utf-8')


def slug(family, weight, style, subset):
    base = re.sub(r'[^a-z0-9]+', '-', family.lower()).strip('-')
    return f"{base}-{weight}{'-italic' if style == 'italic' else ''}-{subset}.woff2"


def main(css_url, out_dir, out_css):
    os.makedirs(out_dir, exist_ok=True)
    css = get(css_url)
    blocks = re.findall(r'(/\* ([a-z-]+) \*/\s*@font-face \{.*?\})', css, re.S)
    kept, total_bytes = [], 0
    for block, subset in blocks:
        if subset not in KEEP:
            continue
        fam = re.search(r"font-family: '([^']+)'", block).group(1)
        wgt = re.search(r'font-weight: ([\d\s]+);', block).group(1).strip()
        sty = re.search(r'font-style: (\w+);', block).group(1)
        url = re.search(r'url\((https://[^)]+\.woff2)\)', block).group(1)
        name = slug(fam, wgt.replace(' ', '-'), sty, subset)
        path = os.path.join(out_dir, name)
        if not os.path.exists(path):
            blob = get(url, binary=True)
            open(path, 'wb').write(blob)
        total_bytes += os.path.getsize(path)
        # relative to fonts.css itself, which lives INSIDE fonts/ — writing
        # './fonts/<name>' here resolves to /fonts/fonts/<name> and 404s
        # silently: the page just renders in the fallback serif.
        block = block.replace(url, f'./{name}')
        # swap: text paints immediately in the fallback, no invisible-text window
        block = re.sub(r'font-display: \w+;', 'font-display: swap;', block)
        if 'font-display' not in block:
            block = block.replace('@font-face {', '@font-face {\n  font-display: swap;')
        kept.append(block)

    header = ('/* Self-hosted fonts — no third-party request, no visitor IP leaves\n'
              '   this origin. Generated by scripts/selfhost-fonts.py; latin +\n'
              '   latin-ext only (the product ships EN + PT). Do not hand-edit. */\n')
    open(out_css, 'w').write(header + '\n'.join(kept) + '\n')
    print(f'{len(kept)} faces, {total_bytes/1024:.1f} KB total → {out_css}')


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
